apiVersion: v1
kind: ConfigMap
metadata:
  name: production-manager-config
  namespace: production
data:
  APP_MODE: "API"
  DB_PORT: "5432"
  DB_HOST: "production-manager-prod-postgres.c0hcysmoeeet.us-east-1.rds.amazonaws.com"
  DB_DATABASE: "production_manager_db"
  DB_USERNAME: "fiap_arch"
  DB_SSL: "false"
