apiVersion: v1
kind: Secret
metadata:
  name: production-manager-secret
  namespace: production
type: Opaque
stringData:
  DB_PASSWORD: "${DB_PASSWORD}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_REGION: "${AWS_REGION}"
  AWS_SQS_QUEUE_URL: "${AWS_SQS_QUEUE_URL}"
  AWS_SNS_TOPIC_ARN: "${AWS_SNS_TOPIC_ARN}"
